# Generated by Django 5.1.1 on 2024-09-11 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_subs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Create_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('nickname', models.CharField(max_length=100)),
                ('happy_birthday', models.DateTimeField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('cpl_status', models.CharField(max_length=100)),
                ('mode_play', models.CharField(max_length=100)),
                ('recruited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.create_subs')),
            ],
        ),
    ]
