# Generated by Django 5.1.1 on 2024-09-11 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_eliminated',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='members_eliminated',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='members_eliminated',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='members_eliminated',
            name='cpl_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='members_eliminated',
            name='happy_birthday',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='members_eliminated',
            name='mode_play',
            field=models.CharField(default='', max_length=100),
        ),
    ]
