# Generated by Django 5.1.1 on 2024-09-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_members_eliminated_age_members_eliminated_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_members',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='members_eliminated',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
